In [1]:
import pandas as pd, ipywidgets as widgets, numpy as np, matplotlib.pyplot as plt, io
raw_uploader = widgets.FileUpload(multiple = False)
platemap1_uploader, platemap2_uploader = widgets.FileUpload(multiple = False), widgets.FileUpload(multiple = False)
first_population_widget = widgets.Text(placeholder='First Pop',description='First Population:', disabled=False)
second_population_widget = widgets.Text(placeholder='Second Pop',description='Second Population:', disabled=False)
plate_num_widget = widgets.IntText(value=0, description='iQue3 Plate Number:', disabled = False)
display("Upload iQue3 Data (csv)")
display(raw_uploader)
display("Upload Antibody Plate Map # 1 (xlsx)")
display(platemap1_uploader)
display("Upload Antibody Plate Map # 2 (xlsx)")
display(platemap2_uploader)
display(first_population_widget)
display(second_population_widget)
display(plate_num_widget)

'Upload iQue3 Data (csv)'

FileUpload(value={}, description='Upload')

'Upload Antibody Plate Map # 1 (xlsx)'

FileUpload(value={}, description='Upload')

'Upload Antibody Plate Map # 2 (xlsx)'

FileUpload(value={}, description='Upload')

Text(value='', description='First Population:', placeholder='First Pop')

Text(value='', description='Second Population:', placeholder='Second Pop')

IntText(value=0, description='iQue3 Plate Number:')

In [2]:
iquename = list(raw_uploader.value.keys())[0]
platemap1_name, platemap2_name = list(platemap1_uploader.value.keys())[0], list(platemap2_uploader.value.keys())[0]
iquedata = pd.read_csv(io.BytesIO(raw_uploader.value[iquename]['content']))
platemap1 = pd.read_excel(io.BytesIO(platemap1_uploader.value[platemap1_name]['content']), sheet_name = "Protein Quant")
platemap2 = pd.read_excel(io.BytesIO(platemap2_uploader.value[platemap2_name]['content']), sheet_name = "Protein Quant")
first_population_name = first_population_widget.value
second_population_name = second_population_widget.value
iquedata.rename(columns = {'Plate' : 'iQue3 Plate','Well ID':'iQue3 384 Well ID', 'Column':'iQue3 Column'}, 
                inplace = True)
platemap1.rename(columns = {'Plate' : 'Antibody Plate','Well ID':'Antibody Platemap 96 Well ID'}, inplace = True)
platemap2.rename(columns = {'Plate' : 'Antibody Plate','Well ID':'Antibody Platemap 96 Well ID'}, inplace = True)
iquedata

,Experiment,Analysis,iQue3 Plate,Export Date and Time,iQue3 384 Well ID,Row,iQue3 Column,Well Type,Count of All Wells,Median BL1-H of singlets,Median RL1-H of singlets,Count of singlets
0,22_10_07 A2a Primary Screen,Analysis 1,A_7,10/10/22 10:39,A01,A,1,Positive,2423,16069276.0,13358.5,344
1,22_10_07 A2a Primary Screen,Analysis 1,A_7,10/10/22 10:39,B01,B,1,Positive,2846,16067215.0,14753.0,563
2,22_10_07 A2a Primary Screen,Analysis 1,A_7,10/10/22 10:39,C01,C,1,Positive,4071,15974982.0,15940.5,842
3,22_10_07 A2a Primary Screen,Analysis 1,A_7,10/10/22 10:39,D01,D,1,Positive,2430,16096966.0,15188.5,562
4,22_10_07 A2a Primary Screen,Analysis 1,A_7,10/10/22 10:39,E01,E,1,Positive,1524,4259308.0,9865.0,71
...,...,...,...,...,...,...,...,...,...,...,...,...
1147,22_10_07 A2a Primary Screen,Analysis 1,U_7,10/10/22 10:39,L24,L,24,Positive,314,10832.5,293932.5,80
1148,22_10_07 A2a Primary Screen,Analysis 1,U_7,10/10/22 10:39,M24,M,24,Positive,516,11963.5,345728.0,260
1149,22_10_07 A2a Primary Screen,Analysis 1,U_7,10/10/22 10:39,N24,N,24,Positive,367,11735.0,308313.0,105
1150,22_10_07 A2a Primary Screen,Analysis 1,U_7,10/10/22 10:39,O24,O,24,Positive,1024,11176.5,318296.5,292
1151,22_10_07 A2a Primary Screen,Analysis 1,U_7,10/10/22 10:39,P24,P,24,Positive,456,11324.0,329140.0,111

In [3]:
data_cleaned = iquedata[["Experiment", "Export Date and Time", "iQue3 Plate", "iQue3 384 Well ID", "iQue3 Column", "Well Type", "Median RL1-H of singlets", "Count of singlets"]]
data_cleaned
platemap1

,Unnamed: 0,IGGP Ticket#,BPP Ticket# (If available),Plate ID/Barcode,Antibody Platemap 96 Well ID,"Sample Name (TB/SC,etc.)",Transfection cell line,Purification Method,Concentration (mg/mL),Transfection scale (mL),Volume (uL),Yield (ug),Lot#,Date Delivered,Requested by
0,NaN,IGGP-383,BPP-XXX,pPUR_R-IGGP-383-220920_002,A1,TB736B-064,Hek293,Batch,0.02,1mL,222,4.44,PROT12490,2022-09-26,NaN
1,NaN,NaN,NaN,NaN,A2,TB736B-076,Hek293,Batch,0.03,1mL,222,6.66,PROT12491,2022-09-26,NaN
2,NaN,NaN,NaN,NaN,A3,TB736B-084,Hek293,Batch,0.00,1mL,222,0.00,PROT12492,2022-09-26,NaN
3,NaN,NaN,NaN,NaN,A4,TB735B-011,Hek293,Batch,0.00,1mL,222,0.00,PROT12493,2022-09-26,NaN
4,NaN,NaN,NaN,NaN,A5,TB735B-019,Hek293,Batch,0.02,1mL,222,4.44,PROT12494,2022-09-26,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,NaN,NaN,NaN,NaN,H8,TB735C-006,Hek293,Batch,0.02,1mL,222,4.44,PROT12581,2022-09-26,NaN
92,NaN,NaN,NaN,NaN,H9,TB735C-014,Hek293,Batch,0.07,1mL,222,15.54,PROT12582,2022-09-26,NaN
93,NaN,NaN,NaN,NaN,H10,TB735C-022,Hek293,Batch,0.60,1mL,222,133.20,PROT12583,2022-09-26,NaN
94,NaN,NaN,NaN,NaN,H11,TB735C-031,Hek293,Batch,0.03,1mL,222,6.66,PROT12584,2022-09-26,NaN
95,NaN,NaN,NaN,NaN,H12,Tmab_220627_KP,Hek293,Batch,2.01,1mL,222,446.22,PROT12585,2022-09-26,NaN

In [4]:
#Function that ensures a given antibody platemap is formatted correctly (by columns, not rows)
#Mutable function that changes the data frame passed in by argument "ab_sheet"
#ie A1->B1-->H1->A2-->B2-->A12-->H12
#First, separate the Well ID into separate "Plate Number","Format Row" and "Format Column" values 
#(Row is Letter, Column is Number)
#Sort the platemap into proper Plate -> Column -> Row format
#Returns nothing, mutates the ab_sheet antibody plate map
def format_platemap(platemap):
    platemap["Format Row"] = platemap["Antibody Platemap 96 Well ID"].str.slice(start = 0, stop = 1)
    numeric_col = platemap["Antibody Platemap 96 Well ID"].str.slice(start = 1)
    numeric_col = pd.to_numeric(numeric_col)
    platemap["Format Column"] = numeric_col
    platemap.sort_values(by=["Plate ID/Barcode","Format Column", "Format Row"], inplace=True, ignore_index = True)
    return

#Return data frame with only samples of the well type specified
def clean_for_well_type(well_type_string):
    return data_cleaned[data_cleaned["Well Type"] == well_type_string]

#Return data frame with only odd or even columns, depending on the remainder given, and of a given plate type
#"remainder": when column is modulo by 2, so 0 are even columns, 1 are odd columns
#plate_type: the letter denoting what population is in the plate, should be the first letter of the plate string
def clean_for_well_type(remainder, plate_type):
    ret_data = data_cleaned[data_cleaned["iQue3 Column"] % 2 == remainder]
    ret_data = ret_data[ret_data["iQue3 Plate"].str.slice(start = 0, stop = 1) == plate_type]
    return ret_data

#Average function that takes a string indicating the well type of interest (marked in iQue3 software, or manually changed
#Separates n=1 and n=2 replicates from 384 well format, resets indeces, and averages
#Returns a series with the averaged MFI ratios, removing the replicate wells
def average_MFI(well_type_string):
    selected_wells = clean_for_well_type(well_type_string)
    MFIs = selected_wells["Median RL1-H of singlets"]
    firsts = MFIs.iloc[::2]
    seconds = MFIs.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    average = firsts + seconds
    average = average/2
    return average

#Average function that takes a remainder and a plate_type to pass to clean_for_well_type
#Separates n=1 and n=2 replicates from 384 well format, resets indeces, and averages
#Returns a series with the averaged MFI ratios, removing the replicate wells
def average_MFI(remainder, plate_type):
    selected_wells = clean_for_well_type(remainder, plate_type)
    MFIs = selected_wells["Median RL1-H of singlets"]
    firsts = MFIs.iloc[::2]
    seconds = MFIs.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    average = firsts + seconds
    average = average/2
    return average

#Calculates the MFI ratio given a positive and negative series, 
#and appends the MFI ratio to the original data frame, excluding the negative population
#first_pop_series: the series of the first population values
#second_pop_series: the series of the second population values
#negative_series: the series of the untransfected population values
#first_population_string: the string that marks the positive samples in the Well Type column from iQue3 csv
#second_population_string: name of the second population
def calculate_analysis_sheet_2pop(first_pop_series, second_pop_series, negative_series, first_population_string, 
                                  second_population_string):
    first_pop_MFI_ratio = first_pop_series/negative_series
    second_pop_MFI_ratio = second_pop_series/negative_series
    original_positive = clean_for_well_type(first_population_string)
    original_positive = original_positive[::2]
    original_positive.reset_index(inplace = True, drop = True)
    original_positive[first_population_string + " MFI Ratio"] = first_pop_MFI_ratio
    original_positive[first_population_string + " Averaged Raw MFI"] = first_pop_series
    original_positive[second_population_string + " MFI Ratio"] = second_pop_MFI_ratio
    original_positive[second_population_string + " Averaged Raw MFI"] = second_pop_series
    original_positive["Parental Averaged Raw MFI"] = negative_series
    analysis_sheet = pd.concat([original_positive, ab_sheet], axis = 1)
    analysis_sheet.index += 1
    analysis_sheet.drop(columns = ['Median RL1-H of singlets'], inplace = True)
    return analysis_sheet

#Calculates the MFI ratio given a positive and negative series, 
#and appends the MFI ratio to the original data frame, excluding the negative population
#first_pop_series: the series of the first population values
#second_pop_series: the series of the second population values
#negative_series: the series of the untransfected population values
#first_population_string: the string that marks the positive samples in the Well Type column from iQue3 csv
#second_population_string: name of the second population
#plate_num: 1 indicates the odd columns, platemap1. 2 indicates even columns, platemap2.
def calculate_analysis_sheet_2pop(first_pop_series, second_pop_series, negative_series, first_population_string, 
                                  second_population_string, plate_num, plate_letter, platemap):
    first_pop_MFI_ratio = first_pop_series/negative_series
    second_pop_MFI_ratio = second_pop_series/negative_series
    original_positive = clean_for_well_type(plate_num%2, plate_letter)
    original_positive = original_positive[::2]
    original_positive.reset_index(inplace = True, drop = True)
    original_positive[first_population_string + " Averaged Raw MFI"] = first_pop_series
    original_positive[second_population_string + " Averaged Raw MFI"] = second_pop_series
    original_positive["Parental Averaged Raw MFI"] = negative_series
    original_positive[first_population_string + " MFI Ratio"] = first_pop_MFI_ratio
    original_positive[second_population_string + " MFI Ratio"] = second_pop_MFI_ratio
    analysis_sheet = pd.concat([original_positive, platemap], axis = 1)
    analysis_sheet.index += 1
    analysis_sheet.drop(columns = ['Export Date and Time', 'Count of singlets','Median RL1-H of singlets', 'Unnamed: 0', 
                                   'Date Delivered', 'Requested by'], inplace = True)
    return analysis_sheet

In [5]:
averageFirstPopulation_P1 = average_MFI(1, "A")
averageFirstPopulation_P2 = average_MFI(0, "A")
averageSecondPopulation_P1 = average_MFI(1, "B")
averageSecondPopulation_P2 = average_MFI(0, "B")
averageParental_P1 = average_MFI(1, "U")
averageParental_P2 = average_MFI(0, "U")
format_platemap(platemap1)
format_platemap(platemap2)

In [6]:
#Create new DF for MFI ratios(don't modify originals)
analyzed_data_p1 = calculate_analysis_sheet_2pop(averageFirstPopulation_P1, averageSecondPopulation_P1,
                                        averageParental_P1, first_population_name, second_population_name, 1, "A", platemap1)
plate1_num = plate_num_widget.value * 2 - 1
plate1_num_str = str(plate1_num)
plate2_num = plate_num_widget.value * 2
plate2_num_str = str(plate2_num)
analyzed_data_p1.to_excel("Plate " + plate1_num_str + " Flow Binding Primary Screen.xlsx", sheet_name='Analyzed Data')
analyzed_data_p1
analyzed_data_p2 = calculate_analysis_sheet_2pop(averageFirstPopulation_P2, averageSecondPopulation_P2,
                                        averageParental_P2, first_population_name, second_population_name, 2, "A", platemap2)
analyzed_data_p2.to_excel("Plate " + plate2_num_str + " Flow Binding Primary Screen.xlsx", sheet_name='Analyzed Data')
analyzed_data_p1
# AllLeadsSorted = analyzed_data.sort_values(by= first_population_name + " MFI Ratio", ascending = False)
# AllLeadsSorted

,Experiment,iQue3 Plate,iQue3 384 Well ID,iQue3 Column,Well Type,A2a Averaged Raw MFI,A2b Averaged Raw MFI,Parental Averaged Raw MFI,A2a MFI Ratio,A2b MFI Ratio,...,"Sample Name (TB/SC,etc.)",Transfection cell line,Purification Method,Concentration (mg/mL),Transfection scale (mL),Volume (uL),Yield (ug),Lot#,Format Row,Format Column
1,22_10_07 A2a Primary Screen,A_7,A01,1,Positive,14055.75,13406.25,13455.00,1.044649,0.996377,...,TB736B-064,Hek293,Batch,0.02,1mL,222,4.44,PROT12490,A,1
2,22_10_07 A2a Primary Screen,A_7,C01,1,Positive,15564.50,13875.00,12911.50,1.205476,1.074623,...,TB736B-065,Hek293,Batch,0.02,1mL,222,4.44,PROT12502,B,1
3,22_10_07 A2a Primary Screen,A_7,E01,1,Positive,11290.00,14498.50,14102.75,0.800553,1.028062,...,TB736B-066,Hek293,Batch,0.01,1mL,222,2.22,PROT12514,C,1
4,22_10_07 A2a Primary Screen,A_7,G01,1,Positive,867429.50,216001.50,30000.25,28.914076,7.199990,...,TB736B-067,Hek293,Batch,2.26,1mL,222,501.72,PROT12526,D,1
5,22_10_07 A2a Primary Screen,A_7,I01,1,Positive,21049.00,18534.00,14317.25,1.470185,1.294522,...,TB736B-069,Hek293,Batch,0.13,1mL,222,28.86,PROT12538,E,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,22_10_07 A2a Primary Screen,A_7,G23,23,Positive,12654.25,13813.50,9989.00,1.266819,1.382871,...,TB735C-035,Hek293,Batch,0.55,1mL,222,122.10,PROT12537,D,12
93,22_10_07 A2a Primary Screen,A_7,I23,23,Positive,10293.50,8854.50,11280.00,0.912544,0.784973,...,TB735C-036,Hek293,Batch,0.00,1mL,222,0.00,PROT12549,E,12
94,22_10_07 A2a Primary Screen,A_7,K23,23,Positive,213823.50,189221.50,281248.50,0.760265,0.672791,...,Tmab_220627_KP,Hek293,Batch,1.77,1mL,222,392.94,PROT12561,F,12
95,22_10_07 A2a Primary Screen,A_7,M23,23,Positive,207182.75,208139.00,332208.25,0.623653,0.626532,...,Tmab_220627_KP,Hek293,Batch,1.57,1mL,222,348.54,PROT12573,G,12
96,22_10_07 A2a Primary Screen,A_7,O23,23,Positive,265724.25,214109.25,283455.50,0.937446,0.755354,...,Tmab_220627_KP,Hek293,Batch,2.01,1mL,222,446.22,PROT12585,H,12

In [ ]:
# #Sort DF by highest MFI ratio (top hits)
# AllLeadsSorted = MFIRatio_Antibody_cleaned.sort_values(by="MFI Ratio", ascending = False)
# Top10 = MFIRatio_Antibody_cleaned.nlargest(10, "MFI Ratio")
# #Top10 = Top10.append(MFIRatio_Antibody_cleaned.loc[MFIRatio_Antibody_cleaned["DNA"] == "SC-175-017"])
# fig, ax = plt.subplots()
# ax.scatter(x = AllLeadsSorted["Protein Concentration (ug/uL)"], y=AllLeadsSorted["MFI Ratio"], alpha = .2, color = "blue")
# ax.scatter(x = Top10["Protein Concentration (ug/uL)"], y = Top10["MFI Ratio"], alpha = .8, color = "blue", label = "Top Hits")
# ax.set_title("CD40 Primary Screen")
# ax.set_xlabel("Concentration (mg/ml)")
# ax.set_ylabel("MFI Ratio \n Transfected/Untransfected")
# ax.legend()

# texts = []
# for row in Top10.itertuples(index = False):
#     ab, conc, MFI = row[4], row[5], row[3]
#     ax.annotate(row[4], xy = (conc, MFI), textcoords = "offset points", xytext = (8, -2), ha ='left')
#     #texts.append(plt.text(ab, conc, MFI))