In [1]:
import pandas as pd, ipywidgets as widgets, numpy as np, matplotlib.pyplot as plt, io
raw_uploader = widgets.FileUpload(multiple = False)
platemap1_uploader, platemap2_uploader = widgets.FileUpload(multiple = False), widgets.FileUpload(multiple = False)
first_population_widget = widgets.Text(placeholder='First Pop',description='First Population:', disabled=False)
second_population_widget = widgets.Text(placeholder='Second Pop',description='Second Population:', disabled=False)
display("Upload iQue3 Data (csv)")
display(raw_uploader)
display("Upload Antibody Plate Map # 1 (xlsx)")
display(platemap1_uploader)
display("Upload Antibody Plate Map # 2 (xlsx)")
display(platemap2_uploader)
display(first_population_widget)
display(second_population_widget)

'Upload iQue3 Data (csv)'

FileUpload(value={}, description='Upload')

'Upload Antibody Plate Map # 1 (xlsx)'

FileUpload(value={}, description='Upload')

'Upload Antibody Plate Map # 2 (xlsx)'

FileUpload(value={}, description='Upload')

Text(value='', description='First Population:', placeholder='First Pop')

Text(value='', description='Second Population:', placeholder='Second Pop')

In [2]:
iquename = list(raw_uploader.value.keys())[0]
platemap1_name, platemap2_name = list(platemap1_uploader.value.keys())[0], list(platemap2_uploader.value.keys())[0]
iquedata = pd.read_csv(io.BytesIO(raw_uploader.value[iquename]['content']))
platemap1 = pd.read_excel(io.BytesIO(platemap1_uploader.value[platemap1_name]['content']), sheet_name = "Protein Quant")
platemap2 = pd.read_excel(io.BytesIO(platemap2_uploader.value[platemap2_name]['content']), sheet_name = "Protein Quant")
first_population_name = first_population_widget.value
second_population_name = second_population_widget.value
iquedata.rename(columns = {'Plate' : 'iQue3 Plate','Well ID':'iQue3 384 Well ID', 'Column':'iQue3 Column'}, 
                inplace = True)
platemap1.rename(columns = {'Plate' : 'Antibody Plate','Well ID':'Antibody Platemap 96 Well ID'}, inplace = True)
platemap2.rename(columns = {'Plate' : 'Antibody Plate','Well ID':'Antibody Platemap 96 Well ID'}, inplace = True)
iquedata

,Experiment,Analysis,iQue3 Plate,Export Date and Time,iQue3 384 Well ID,Row,iQue3 Column,Well Type,Count of All Wells,Median BL1-H of singlets,Median RL1-H of singlets,Count of singlets
0,22_10_03 A2a Primary Screen,Analysis 1,A_1,10/3/22 16:58,A01,A,1,Positive,2837,16091273.0,497495.0,769
1,22_10_03 A2a Primary Screen,Analysis 1,A_1,10/3/22 16:58,B01,B,1,Positive,3588,16048798.0,467772.0,661
2,22_10_03 A2a Primary Screen,Analysis 1,A_1,10/3/22 16:58,C01,C,1,Positive,3210,16093385.0,98102.0,438
3,22_10_03 A2a Primary Screen,Analysis 1,A_1,10/3/22 16:58,D01,D,1,Positive,4293,15962445.0,91465.0,457
4,22_10_03 A2a Primary Screen,Analysis 1,A_1,10/3/22 16:58,E01,E,1,Positive,5349,13290438.0,414277.5,830
...,...,...,...,...,...,...,...,...,...,...,...,...
1147,22_10_03 A2a Primary Screen,Analysis 1,U_1,10/3/22 16:58,L24,L,24,Positive,828,12438.5,276400.0,284
1148,22_10_03 A2a Primary Screen,Analysis 1,U_1,10/3/22 16:58,M24,M,24,Positive,1056,12649.0,268237.0,465
1149,22_10_03 A2a Primary Screen,Analysis 1,U_1,10/3/22 16:58,N24,N,24,Positive,1043,12913.0,302940.0,497
1150,22_10_03 A2a Primary Screen,Analysis 1,U_1,10/3/22 16:58,O24,O,24,Positive,1177,12524.5,286271.5,528
1151,22_10_03 A2a Primary Screen,Analysis 1,U_1,10/3/22 16:58,P24,P,24,Positive,1126,12204.0,250613.0,471

In [14]:
data_cleaned = iquedata[["Experiment", "Export Date and Time", "iQue3 Plate", "iQue3 384 Well ID", "iQue3 Column", "Well Type", "Median RL1-H of singlets", "Count of singlets"]]
data_cleaned

,Experiment,Export Date and Time,iQue3 Plate,iQue3 384 Well ID,iQue3 Column,Well Type,Median RL1-H of singlets,Count of singlets
0,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,A01,1,Positive,497495.0,769
1,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,B01,1,Positive,467772.0,661
2,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,C01,1,Positive,98102.0,438
3,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,D01,1,Positive,91465.0,457
4,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,E01,1,Positive,414277.5,830
...,...,...,...,...,...,...,...,...
1147,22_10_03 A2a Primary Screen,10/3/22 16:58,U_1,L24,24,Positive,276400.0,284
1148,22_10_03 A2a Primary Screen,10/3/22 16:58,U_1,M24,24,Positive,268237.0,465
1149,22_10_03 A2a Primary Screen,10/3/22 16:58,U_1,N24,24,Positive,302940.0,497
1150,22_10_03 A2a Primary Screen,10/3/22 16:58,U_1,O24,24,Positive,286271.5,528
1151,22_10_03 A2a Primary Screen,10/3/22 16:58,U_1,P24,24,Positive,250613.0,471

In [21]:
#Return data frame with only samples of the well type specified
def clean_for_well_type(well_type_string):
    return data_cleaned[data_cleaned["Well Type"] == well_type_string]

#Return data frame with only odd or even columns, depending on the remainder given, and of a given plate type
#"remainder": when column is modulo by 2, so 0 are even columns, 1 are odd columns
#plate_type: the letter denoting what population is in the plate, should be the first letter of the plate string
def clean_for_well_type(remainder, plate_type):
    ret_data = data_cleaned[data_cleaned["iQue3 Column"] % 2 == remainder]
    ret_data = ret_data[ret_data["iQue3 Plate"].str.slice(start = 0, stop = 1) == plate_type]
    return ret_data

#Average function that takes a string indicating the well type of interest (marked in iQue3 software, or manually changed
#Separates n=1 and n=2 replicates from 384 well format, resets indeces, and averages
#Returns a series with the averaged MFI ratios, removing the replicate wells
def average_MFI(well_type_string):
    selected_wells = clean_for_well_type(well_type_string)
    MFIs = selected_wells["Median RL1-H of singlets"]
    firsts = MFIs.iloc[::2]
    seconds = MFIs.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    average = firsts + seconds
    average = average/2
    return average

#Average function that takes a remainder and a plate_type to pass to clean_for_well_type
#Separates n=1 and n=2 replicates from 384 well format, resets indeces, and averages
#Returns a series with the averaged MFI ratios, removing the replicate wells
def average_MFI(remainder, plate_type):
    selected_wells = clean_for_well_type(remainder, plate_type)
    MFIs = selected_wells["Median RL1-H of singlets"]
    firsts = MFIs.iloc[::2]
    seconds = MFIs.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    average = firsts + seconds
    average = average/2
    return average

#Calculates the MFI ratio given a positive and negative series, 
#and appends the MFI ratio to the original data frame, excluding the negative population
#first_pop_series: the series of the first population values
#second_pop_series: the series of the second population values
#negative_series: the series of the untransfected population values
#first_population_string: the string that marks the positive samples in the Well Type column from iQue3 csv
#second_population_string: name of the second population
def calculate_analysis_sheet_2pop(first_pop_series, second_pop_series, negative_series, first_population_string, 
                                  second_population_string):
    first_pop_MFI_ratio = first_pop_series/negative_series
    second_pop_MFI_ratio = second_pop_series/negative_series
    original_positive = clean_for_well_type(first_population_string)
    original_positive = original_positive[::2]
    original_positive.reset_index(inplace = True, drop = True)
    original_positive[first_population_string + " MFI Ratio"] = first_pop_MFI_ratio
    original_positive[first_population_string + " Averaged Raw MFI"] = first_pop_series
    original_positive[second_population_string + " MFI Ratio"] = second_pop_MFI_ratio
    original_positive[second_population_string + " Averaged Raw MFI"] = second_pop_series
    original_positive["Parental Averaged Raw MFI"] = negative_series
    analysis_sheet = pd.concat([original_positive, ab_sheet], axis = 1)
    analysis_sheet.index += 1
    analysis_sheet.drop(columns = ['Median RL1-H of singlets'], inplace = True)
    return analysis_sheet

#Calculates the MFI ratio given a positive and negative series, 
#and appends the MFI ratio to the original data frame, excluding the negative population
#first_pop_series: the series of the first population values
#second_pop_series: the series of the second population values
#negative_series: the series of the untransfected population values
#first_population_string: the string that marks the positive samples in the Well Type column from iQue3 csv
#second_population_string: name of the second population
#plate_num: 1 indicates the odd columns, platemap1. 2 indicates even columns, platemap2.
def calculate_analysis_sheet_2pop(first_pop_series, second_pop_series, negative_series, first_population_string, 
                                  second_population_string, plate_num, plate_letter, platemap):
    first_pop_MFI_ratio = first_pop_series/negative_series
    second_pop_MFI_ratio = second_pop_series/negative_series
    original_positive = clean_for_well_type(plate_num%2, plate_letter)
    original_positive = original_positive[::2]
    original_positive.reset_index(inplace = True, drop = True)
    original_positive[first_population_string + " Averaged Raw MFI"] = first_pop_series
    original_positive[second_population_string + " Averaged Raw MFI"] = second_pop_series
    original_positive["Parental Averaged Raw MFI"] = negative_series
    original_positive[first_population_string + " MFI Ratio"] = first_pop_MFI_ratio
    original_positive[second_population_string + " MFI Ratio"] = second_pop_MFI_ratio
    analysis_sheet = pd.concat([original_positive, platemap], axis = 1)
    analysis_sheet.index += 1
    analysis_sheet.drop(columns = ['Median RL1-H of singlets', 'Unnamed: 0'], inplace = True)
    return analysis_sheet

In [22]:
averageFirstPopulation_P1 = average_MFI(1, "A")
averageFirstPopulation_P2 = average_MFI(0, "A")
averageSecondPopulation_P1 = average_MFI(1, "B")
averageSecondPopulation_P2 = average_MFI(0, "B")
averageParental_P1 = average_MFI(1, "U")
averageParental_P2 = average_MFI(0, "U")

In [23]:
#Create new DF for MFI ratios(don't modify originals)
analyzed_data_p1 = calculate_analysis_sheet_2pop(averageFirstPopulation_P1, averageSecondPopulation_P1,
                                        averageParental_P1, first_population_name, second_population_name, 1, "A", platemap1)
analyzed_data_p1.to_excel("Plate 1 Flow Binding Primary Screen.xlsx", sheet_name='Analyzed Data')
analyzed_data_p1
analyzed_data_p2 = calculate_analysis_sheet_2pop(averageFirstPopulation_P2, averageSecondPopulation_P2,
                                        averageParental_P2, first_population_name, second_population_name, 2, "A", platemap2)
analyzed_data_p2.to_excel("Plate 2 Flow Binding Primary Screen.xlsx", sheet_name='Analyzed Data')
analyzed_data_p1
# AllLeadsSorted = analyzed_data.sort_values(by= first_population_name + " MFI Ratio", ascending = False)
# AllLeadsSorted

,Experiment,Export Date and Time,iQue3 Plate,iQue3 384 Well ID,iQue3 Column,Well Type,Count of singlets,A2a Averaged Raw MFI,A2b Averaged Raw MFI,Parental Averaged Raw MFI,...,"Sample Name (TB/SC,etc.)",Transfection cell line,Purification Method,Concentration (mg/mL),Transfection scale (mL),Volume (uL),Yield (ug),Lot#,Date Delivered,Requested by
1,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,A01,1,Positive,769,482633.50,185851.25,23583.00,...,PRJ135A-067,Hek293,Batch,1.41,1mL,222,313.02,PROT12692,2022-09-27,NaN
2,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,C01,1,Positive,438,94783.50,20327.00,12186.50,...,PRJ135A-080,Hek293,Batch,0.68,1mL,222,150.96,PROT12693,2022-09-27,NaN
3,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,E01,1,Positive,830,436155.50,128395.75,82637.00,...,PRJ135A-091,Hek293,Batch,0.89,1mL,222,197.58,PROT12694,2022-09-27,NaN
4,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,G01,1,Positive,396,596883.50,85497.25,35371.25,...,PRJ135A-102,Hek293,Batch,0.00,1mL,222,0.00,PROT12695,2022-09-27,NaN
5,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,I01,1,Positive,937,816941.25,158862.00,44719.00,...,PRJ135A-113,Hek293,Batch,0.41,1mL,222,91.02,PROT12696,2022-09-27,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,G23,23,Positive,457,132272.25,116650.25,20127.25,...,PRJ135A-154,Hek293,Batch,0.02,1mL,222,4.44,PROT12783,2022-09-27,NaN
93,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,I23,23,Positive,145,44775.00,21889.25,10030.75,...,PRJ135A-162,Hek293,Batch,0.53,1mL,222,117.66,PROT12784,2022-09-27,NaN
94,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,K23,23,Positive,362,154853.50,133939.25,250975.00,...,PRJ135A-172,Hek293,Batch,0.54,1mL,222,119.88,PROT12785,2022-09-27,NaN
95,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,M23,23,Positive,191,154525.50,131927.75,257023.50,...,PRJ135A-187,Hek293,Batch,0.52,1mL,222,115.44,PROT12786,2022-09-27,NaN
96,22_10_03 A2a Primary Screen,10/3/22 16:58,A_1,O23,23,Positive,364,149586.50,143362.00,238767.00,...,Tmab_220627_KP,Hek293,Batch,1.41,1mL,222,313.02,PROT12787,2022-09-27,NaN

In [ ]:
# #Sort DF by highest MFI ratio (top hits)
# AllLeadsSorted = MFIRatio_Antibody_cleaned.sort_values(by="MFI Ratio", ascending = False)
# Top10 = MFIRatio_Antibody_cleaned.nlargest(10, "MFI Ratio")
# #Top10 = Top10.append(MFIRatio_Antibody_cleaned.loc[MFIRatio_Antibody_cleaned["DNA"] == "SC-175-017"])
# fig, ax = plt.subplots()
# ax.scatter(x = AllLeadsSorted["Protein Concentration (ug/uL)"], y=AllLeadsSorted["MFI Ratio"], alpha = .2, color = "blue")
# ax.scatter(x = Top10["Protein Concentration (ug/uL)"], y = Top10["MFI Ratio"], alpha = .8, color = "blue", label = "Top Hits")
# ax.set_title("CD40 Primary Screen")
# ax.set_xlabel("Concentration (mg/ml)")
# ax.set_ylabel("MFI Ratio \n Transfected/Untransfected")
# ax.legend()

# texts = []
# for row in Top10.itertuples(index = False):
#     ab, conc, MFI = row[4], row[5], row[3]
#     ax.annotate(row[4], xy = (conc, MFI), textcoords = "offset points", xytext = (8, -2), ha ='left')
#     #texts.append(plt.text(ab, conc, MFI))