In [3]:
import pandas as pd, ipywidgets as widgets, numpy as np, matplotlib.pyplot as plt, io
from adjustText import adjust_text
raw_uploader, eln_uploader = widgets.FileUpload(multiple = False), widgets.FileUpload(multiple = False)
display("Upload iQue3 Data (csv)")
display(raw_uploader)
display("Upload ELN w/ Antibodies Sheet (xlsx)")
display(eln_uploader)

'Upload iQue3 Data (csv)'

FileUpload(value={}, description='Upload')

'Upload ELN w/ Antibodies Sheet (xlsx)'

FileUpload(value={}, description='Upload')

In [4]:
iquename, elnname = list(raw_uploader.value.keys())[0], list(eln_uploader.value.keys())[0]
iquename
iquedata = pd.read_csv(io.BytesIO(raw_uploader.value[iquename]['content']))
eln = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']))
ab_sheet = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']), sheet_name = "Antibody Plate Map")
iquedata

,Experiment,Analysis,Plate,Export Date and Time,Well ID,Row,Column,Well Type,Count of All Wells,Median BL1-H of transfected_binding,Median RL1-H of transfected_binding,Count of transfected_binding,Median BL1-H of untransfected_nonspecific,Median RL1-H of untransfected_nonspecific,Count of untransfected_nonspecific,Median BL1-H of singlets,Median RL1-H of singlets,Count of singlets
0,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,A01,A,1,FL,4469,30086.0,666708.0,33,15183.0,1302361.0,399,15800.0,1263677.0,500
1,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,B01,B,1,FL,5204,34608.0,1005294.0,69,15650.0,1412448.0,693,16409.5,1374862.5,872
2,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,C01,C,1,FL,5394,27611.0,299447.5,206,14995.0,601304.5,368,16324.0,332313.0,971
3,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,D01,D,1,FL,4253,28412.0,314210.0,91,14313.0,690449.5,262,15908.0,413483.5,564
4,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,E01,E,1,FL,2983,30956.5,776430.0,28,15856.0,4520464.0,632,16239.0,4340748.5,702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,D21,D,21,Negative,1290,27960.0,168249.0,1,12919.5,8476231.0,4,14383.0,18101.0,310
212,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,E21,E,21,Negative,1018,51776.0,514266.0,8,10650.0,471639.0,5,13798.0,22063.0,195
213,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,F21,F,21,Negative,1327,47148.5,486591.5,8,15474.5,946050.0,10,14993.5,15716.0,538
214,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,G21,G,21,Negative,893,56755.5,524788.5,8,14439.5,6410252.5,4,14967.0,13837.0,173
215,22_01_24 TREM1 Expi293 Top Hit Scale Up Primary,Analysis 1,TREM1 Expi293 Top Hit Scale Up Primary,1/25/22 11:59,H21,H,21,Negative,890,37564.5,654699.5,6,14870.0,6183062.0,5,14502.0,15198.0,191

In [5]:
data_cleaned = iquedata[["Plate", "Well ID", "Well Type", "Median RL1-H of singlets"]]
data_cleaned

,Plate,Well ID,Well Type,Median RL1-H of singlets
0,TREM1 Expi293 Top Hit Scale Up Primary,A01,FL,1263677.0
1,TREM1 Expi293 Top Hit Scale Up Primary,B01,FL,1374862.5
2,TREM1 Expi293 Top Hit Scale Up Primary,C01,FL,332313.0
3,TREM1 Expi293 Top Hit Scale Up Primary,D01,FL,413483.5
4,TREM1 Expi293 Top Hit Scale Up Primary,E01,FL,4340748.5
...,...,...,...,...
211,TREM1 Expi293 Top Hit Scale Up Primary,D21,Negative,18101.0
212,TREM1 Expi293 Top Hit Scale Up Primary,E21,Negative,22063.0
213,TREM1 Expi293 Top Hit Scale Up Primary,F21,Negative,15716.0
214,TREM1 Expi293 Top Hit Scale Up Primary,G21,Negative,13837.0
215,TREM1 Expi293 Top Hit Scale Up Primary,H21,Negative,15198.0

In [ ]:
def average(well_type_string):
    selected_wells = data_cleaned[data_cleaned["Well Type"] == well_type_string]
    MFIs = selected_well["Median RL1-H of singlets"]
    firsts = MFIS.iloc[::2]
    seconds = MFIS.iloc[1:2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    average = firsts _

In [ ]:
#Create a series with only the Positive population from plate, and another series with only those MFIs
#Separate n=1 and n=2 duplicates, average them and reset the indeces
only_positive = data_cleaned[data_cleaned["Well Type"] == "Positive"]
positives_MFI = only_positive["Median RL1-H of singlets"]
firsts = positives_MFI.iloc[::2]
seconds = positives_MFI.iloc[1::2]
firsts.reset_index(inplace = True, drop = True)
seconds.reset_index(inplace = True, drop = True)
averagePositive = firsts + seconds
averagePositive = averagePositive / 2

In [ ]:
#Do the same with the Negative population (untransfected controls)
only_negative = data_cleaned[data_cleaned["Well Type"] == "Negative"]
negatives_MFI = only_negative["Median RL1-H of singlets"]
negatives_MFI.reset_index(inplace = True, drop = True)
firsts = negatives_MFI.iloc[::2]
seconds = negatives_MFI.iloc[1::2]
firsts.reset_index(inplace = True, drop = True)
seconds.reset_index(inplace = True, drop = True)
averageNegative = firsts + seconds
averageNegative = averageNegative / 2

#averageNegative

In [ ]:
#Create new DF for MFI ratios(don't modify originals)
MFIratios = averagePositive / averageNegative
positives_MFIratio = only_positive.copy()
positives_MFIratio = positives_MFIratio[::2]
positives_MFIratio.reset_index(inplace = True, drop = True)
positives_MFIratio["MFI Ratio"] = MFIratios

MFIRatio_Antibody = pd.concat([positives_MFIratio, ab_sheet], axis = 1)
#MFIRatio_Antibody
MFIRatio_Antibody_cleaned = MFIRatio_Antibody[["Plate", "Well ID", "Well Type", "MFI Ratio", "DNA", "Protein Concentration (ug/uL)"]]
#MFIRatio_Antibody_cleaned = MFIRatio_Antibody_cleaned[MFIRatio_Antibody_cleaned["DNA"].notna()]
MFIRatio_Antibody_cleaned.to_excel("Well_ID_MFI_Ratio.xlsx")
AllLeadsSorted = MFIRatio_Antibody_cleaned.sort_values(by="MFI Ratio", ascending = False)
AllLeadsSorted

In [ ]:
#Sort DF by highest MFI ratio (top hits)
AllLeadsSorted = MFIRatio_Antibody_cleaned.sort_values(by="MFI Ratio", ascending = False)
Top10 = MFIRatio_Antibody_cleaned.nlargest(10, "MFI Ratio")
#Top10 = Top10.append(MFIRatio_Antibody_cleaned.loc[MFIRatio_Antibody_cleaned["DNA"] == "SC-175-017"])
fig, ax = plt.subplots()
ax.scatter(x = AllLeadsSorted["Protein Concentration (ug/uL)"], y=AllLeadsSorted["MFI Ratio"], alpha = .2, color = "blue")
ax.scatter(x = Top10["Protein Concentration (ug/uL)"], y = Top10["MFI Ratio"], alpha = .8, color = "blue", label = "Top Hits")
ax.set_title("CD40 Primary Screen")
ax.set_xlabel("Concentration (mg/ml)")
ax.set_ylabel("MFI Ratio \n Transfected/Untransfected")
ax.legend()

texts = []
for row in Top10.itertuples(index = False):
    ab, conc, MFI = row[4], row[5], row[3]
    ax.annotate(row[4], xy = (conc, MFI), textcoords = "offset points", xytext = (8, -2), ha ='left')
    #texts.append(plt.text(ab, conc, MFI))