In [1]:
import pandas as pd, ipywidgets as widgets, numpy as np, matplotlib.pyplot as plt, io
raw_uploader, eln_uploader = widgets.FileUpload(multiple = False), widgets.FileUpload(multiple = False)
display("Upload ELN w/ Reporter Data and Antibodies Sheet (xlsx)")
display(eln_uploader)

'Upload ELN w/ Reporter Data and Antibodies Sheet (xlsx)'

FileUpload(value={}, description='Upload')

In [2]:
elnname = list(eln_uploader.value.keys())[0]
eln = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']))
reporter_antagonist_data = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']), sheet_name = "Reporter Antagonist")
ab_sheet = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']), sheet_name = "Antibody Plate Map")
reporter_antagonist_data

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,0.134289,0.331863,0.248631,0.241285,0.220067,0.307484,0.197767,0.264616,0.256205,0.256819,0.325237,0.303635,0.240393,0.194967,0.270366,0.265014,0.300588,0.327428,0.231633,0.248490
1,0.233488,0.192437,0.301686,0.243851,0.260329,0.257714,0.267366,0.213825,0.210135,0.229278,0.119636,0.237629,0.258716,0.209130,0.175523,0.244713,0.319651,0.231910,0.160401,0.281246
2,0.141712,0.182131,0.070633,0.100717,0.249090,0.195206,0.071941,0.090925,0.198675,0.192481,0.050239,0.044248,0.117015,0.111026,0.253164,0.098325,0.235777,0.271903,0.194800,0.219416
3,0.105590,0.066847,0.114215,0.285243,0.188466,0.064562,0.080789,0.057264,0.232865,0.124888,0.248798,0.235899,0.252446,0.254586,0.225046,0.136355,0.297179,0.087711,0.168760,0.186021
4,0.114018,0.070267,0.037302,0.115688,0.036185,0.038368,0.064978,0.015737,0.067444,0.040287,0.053321,0.258262,0.268083,0.319417,0.128879,0.084673,0.293333,0.064458,0.057456,NaN
5,0.208820,0.201336,0.092119,0.033895,0.018446,0.071404,0.177767,0.023422,0.019276,0.046484,0.024632,0.066622,0.061979,0.108086,0.035970,0.062948,0.232890,0.067899,0.040286,NaN
6,0.066700,0.041472,0.061040,0.023791,0.031049,0.058838,0.192074,0.039497,0.023242,0.013194,0.061663,0.048577,0.081662,0.023100,0.036341,0.024076,0.052223,0.063947,0.032315,NaN
7,0.118715,0.057934,0.048493,0.079775,0.246496,0.109349,0.046772,0.067899,0.042611,0.065853,0.222043,0.154910,0.082555,0.078822,0.052321,0.057370,0.120474,0.084433,0.027432,NaN
8,0.245309,0.169821,0.108883,0.194935,0.026085,0.051823,0.223815,0.218884,0.094304,0.087288,0.215382,0.080008,0.188576,0.195470,0.104913,0.261365,0.305757,0.203365,0.123013,NaN
9,0.244584,0.233946,0.197965,0.232611,0.087118,0.242949,0.145439,0.222470,0.270846,0.193432,0.205719,0.266301,0.193885,0.306461,0.163030,0.286715,0.111907,0.202300,0.192637,NaN
10,0.192089,0.256751,0.190847,0.190126,0.228100,0.211373,0.187494,0.228001,0.227952,0.222222,0.321053,0.268453,0.288624,0.276150,0.210871,0.324678,0.239202,0.276467,0.160095,NaN
11,0.234818,0.207611,0.201241,0.236242,0.222374,0.261931,0.289536,0.222576,0.195705,0.184876,0.245824,0.187935,0.242230,0.239317,0.278090,0.308687,0.220762,0.217451,0.188815,NaN
12,0.240809,0.243661,0.240645,0.200320,0.266885,0.288214,0.281222,0.229245,0.233495,0.166630,0.202722,0.225698,0.199806,0.312005,0.270691,0.251290,0.237575,0.245568,0.206041,NaN
13,0.295151,0.202712,0.251791,0.273381,0.267501,0.269776,0.199764,0.218861,0.193740,0.202145,0.221558,0.211393,0.251568,0.244582,0.175195,0.219765,0.193881,0.198655,0.245232,NaN
14,0.232602,0.173207,0.407742,0.245763,0.247506,0.233999,0.215601,0.229885,0.230939,0.231950,0.244378,0.257065,0.209869,0.304421,0.210048,0.268692,0.318694,0.215750,0.249031,NaN
15,0.442202,0.278145,0.294356,0.258164,0.267284,0.329595,0.249710,0.303547,0.241880,0.256144,0.263106,0.349372,0.360262,0.290383,0.207770,0.382676,0.253848,0.383603,0.802219,NaN

In [4]:
#Function that ensures a given antibody platemap is formatted correctly (by columns, not rows)
#ie A1->B1-->H1->A2-->B2-->A12-->H12
#Currently only working for single platemap, not multiple platemaps merged and identified by a plate number
#First, separate the Well ID into separate Row and Column values (Row is Letter, Column is Number)
#Sort the platemap into proper Column -> Row format
#Returns a new dataframe that is exactly ab_sheet, but sorted/formatted correctly
def format_platemap():
    ab_sheet["Format Row"] = ab_sheet["Well ID"].str.slice(start = 0, stop = 1)
    numeric_col = ab_sheet["Well ID"].str.slice(start = 1)
    numeric_col = pd.to_numeric(numeric_col)
    ab_sheet["Format Column"] = numeric_col
    ab_sheet.sort_values(by=["Format Column", "Format Row"], inplace=True, ignore_index = True)
    return

#Return data frame with only samples of the well type specified
def clean_for_well_type(well_type_string):
    return data_cleaned[data_cleaned["Well Type"] == well_type_string]

#Average function that takes a string indicating the well type of interest (marked in iQue3 software, or manually changed in csv)
#Also takes a string indicating the data from the csv to be averaged (to_average_string)
#Separates n=1 and n=2 replicates from 384 well format, resets indeces, and averages
#Returns a series with the averaged MFI ratios, removing the replicate wells
# def average_MFI(well_type_string):
#     selected_wells = clean_for_well_type(well_type_string)
#     MFIs = selected_wells["Median RL1-H of singlets"]
#     firsts = MFIs.iloc[::2]
#     seconds = MFIs.iloc[1::2]
#     firsts.reset_index(inplace = True, drop = True)
#     seconds.reset_index(inplace = True, drop = True)
#     average = firsts + seconds
#     average = average/2
#     return average
def average(well_type_string, to_average_string):
    selected_wells = clean_for_well_type(well_type_string)
    values_to_average = selected_wells[to_average_string]
    return average(values_to_average)

#Average function that takes a series with n=1, n=2 replicates in sequential order within the series, and 
#Separates n=1 and n=2 replicates resets indeces, and calculates average
#Returns a series with the averaged MFI ratios, removing the replicate wells
def average(series_to_average):
    firsts = series_to_average.iloc[::2]
    seconds = series_to_average.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    averaged_series = firsts + seconds
    averaged_series = averaged_series/2
    return averaged_series

#Calculates the MFI ratio given a positive and negative series, 
#and appends the MFI ratio to the original data frame, excluding the negative population
#Calculates the average cell count for each duplicate, and appends average cell count to original data frame
def calculate_analysis_sheet(positive, negative):
    MFI_ratio = positive/negative
    original_positive = clean_for_well_type("Positive")
    original_positive = original_positive[::2]
    original_positive.reset_index(inplace = True, drop = True)
    original_positive["MFI Ratio"] = MFI_ratio
    MFIs_Antibody = pd.concat([original_positive, ab_sheet], axis = 1)
    MFIs_Antibody.index += 1
    averagePositiveCounts = average("Positive", "Count of singlets")
    return MFIs_Antibody[["Plate", "Well ID", "Well Type", "MFI Ratio", "DNA", "Format Row", "Format Column"]] 

#Takes a Pandas dataframe as an input. Takes every column from the dataframe and concatenates them into one single series
#Returns the new series that has all of the data in one column, starting from 1st column -> max # of columns
def columnize(df_to_columnize):
    return_column = pd.Series()
    for column in df_to_columnize.columns:
        colToAdd = df_to_columnize[column]
        return_column = pd.concat([return_column, colToAdd], axis = 0, ignore_index = True)
    return return_column

In [5]:
#Create new DF for concatenating the Agonist, Antagonist signals, and the Antibody Plate Map
format_platemap()
antagonists_in_column = columnize(reporter_antagonist_data)
averageAntagonists = average(antagonists_in_column)
OutputSheet = pd.concat([averageAntagonists, ab_sheet], axis = 1)
OutputSheet.index += 1
OutputSheet.rename(inplace = True, columns = {0: "Antagonist Mode"})
OutputSheetCleaned = OutputSheet[["Antagonist Mode", "DNA", "Concentration (mg/mL)"]]
OutputSheetCleaned.to_excel("Reporter_Output.xlsx")
AntagonistSort = OutputSheetCleaned.sort_values(by="Antagonist Mode", ascending = False)

/var/folders/k8/mg372j_55z30k1z4y_8mb0w00000gn/T/ipykernel_45500/516407805.py:67: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return_column = pd.Series()

NameError: name 'values_to_average' is not defined

In [ ]:
# Top10Antagonists = OutputSheetCleaned.nsmallest(10, "Antagonist Mode")
# fig, ax = plt.subplots()
# ax.scatter(x = OutputSheetCleaned["Protein Concentration (ug/uL)"], y=OutputSheetCleaned["Antagonist Mode"], alpha = .2, color = "red")
# ax.scatter(x = Top10Antagonists["Protein Concentration (ug/uL)"], y = Top10Antagonists["Antagonist Mode"], alpha = .8, color = "red", label = "Top Antagonist Hits")
# ax.set_title("BRET Primary Screen")
# ax.set_xlabel("Concentration (mg/ml)")
# ax.set_ylabel("cAMP Levels")
# ax.legend()