In [1]:
%matplotlib inline
import pandas as pd, ipywidgets as widgets, numpy as np, matplotlib.pyplot as plt, io
import string, math
from ipywidgets import interact, interactive, fixed, interact_manual

#Standard functions

#Function that ensures a given antibody platemap is formatted correctly (by columns, not rows)
#Mutable function that changes the data frame passed in by argument "ab_sheet"
#ie A1->B1-->H1->A2-->B2-->A12-->H12
#First, separate the Well ID into separate "Plate Number","Format Row" and "Format Column" values 
#(Row is Letter, Column is Number)
#Sort the platemap into proper Plate -> Column -> Row format
#Returns nothing, mutates the ab_sheet antibody plate map
def format_platemap(ab_sheet):
    ab_sheet["Format Row"] = ab_sheet["Well ID"].str.slice(start = 0, stop = 1)
    numeric_col = ab_sheet["Well ID"].str.slice(start = 1)
    numeric_col = pd.to_numeric(numeric_col)
    ab_sheet["Format Column"] = numeric_col
    ab_sheet.sort_values(by=["Plate Number","Format Column", "Format Row"], inplace=True, ignore_index = True)
    return

#Average function that takes a series with n=1, n=2 replicates in sequential order within the series, and 
#Separates n=1 and n=2 replicates resets indeces, and calculates average
#Returns a series with the averaged values, removing the replicate wells
def average(series_to_average):
    firsts = series_to_average.iloc[::2]
    seconds = series_to_average.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    averaged_series = firsts + seconds
    averaged_series = averaged_series/2
    return averaged_series

#Takes a Pandas dataframe as an input. Takes every column from the dataframe and concatenates them into one single series
#Returns the new series that has all of the data in one column, starting from 1st column -> max # of columns
def columnize(df_to_columnize):
    return_column = pd.Series()
    for column in df_to_columnize.columns:
        colToAdd = df_to_columnize[column]
        return_column = pd.concat([return_column, colToAdd], axis = 0, ignore_index = True)
    return return_column

In [19]:
#New functions written for M5 analysis

#Average function that returns an average series but also a series of the standard deviations for each average
def average_stddev(series_to_average):
    firsts = series_to_average.iloc[::2]
    seconds = series_to_average.iloc[1::2]
    firsts.reset_index(inplace = True, drop = True)
    seconds.reset_index(inplace = True, drop = True)
    averaged_series = firsts + seconds
    averaged_series = averaged_series/2
    stddev = (((firsts - averaged_series) ** 2) + ((seconds - averaged_series) ** 2) / 2) ** .5
    return averaged_series, stddev

#Parse data from the xlsx format from M5. Splits the raw data file into plates, not analysis ready, 
#and return a dictionary of {plate number : uncleaned data} key value pairs
#Accepts a Pandas dataframe that is the raw data from the M5, number of blocks in the raw data, 
#and the blocksize (default = 20)
def parse(data, numblocks, blocksize = 20):
    parsed_dict = {}
    for i in range(numblocks):
        rowstart = 0 + blocksize * i
        rowend = 18 + blocksize * i
        df = data.iloc[rowstart:rowend, 0:26]
        df.reset_index(inplace = True, drop = True)
        parsed_dict[i+1] = df
    return parsed_dict
        
#For each plate parsed, clean unnecessary data and return a dictionary of {plate name: cleaned data} key value pairs
#Accepts a dictionary of raw plates. Cleans each plate and renames axes to proper 384 well format
#Cleaning the plate means reformatting the data into a pandas DataFrame with proper multi-indexing: 8 Rows with n = 1/2
#for each row. 
#Returns a dictionary of cleaned plates
def clean(parsedplates):    
    cleaned_dict = {}
    for key, plate in parsedplates.items():
        platename = plate[1][0]
        data = plate.iloc[2:, 2:27].reset_index(drop = True)

        rows = list(range(1, 9))
        ns = [1, 2]
        multidex_array = [rows, ns]
        multidex = pd.MultiIndex.from_product(multidex_array, names = ["Row", "n"])
        
        cleaned = pd.DataFrame(data.values, index = multidex)
        cleaned.rename(columns = dict(zip(list(cleaned.columns), list(range(1, 25)))), inplace = True)
        cleaned.rename_axis("Column", axis = "columns", inplace = True)
        cleaned_dict[platename] = cleaned
    return cleaned_dict

#Function to divide one plate by another. Check keys. Plate name should be organized in 
#"*Target* *Assay*"" format, with assay being the last substring after a space. 
# platedic - a dictionary of {Plate Name: Data} key/value pairs to perform the division on
# assaynum - a string of the name of the assay that should be the numerator (FFLuc in NanoLuc, Venus in BRET)
# assyden - a string of the name of assay that should be the denominator (RLuc in NanoLuc)
# Returns a new dictionary with the {receptorname_assaynum/assayden : divided data} key value pairs.
def divplate(platedic, assaynum, assayden):
    divdict = {}
    plates = platedic.keys()
    for key in plates:
        receptor = key[:len(key) - len(assaynum)]
        receptorden = receptor + assayden
        if assaynum in key and receptorden in plates:
            divdict[f"{key}-{assayden}"] = platedic[key] / platedic[receptorden] 
    return divdict

#Averages n=1 and n=2 duplicates in a 384 well plate
#Accepts a dictionary of cleaned plates, and returns a dictionary of {plate name: averaged}
#and a dictionary of {plate name: standard deviation}
def average_plates(platestoaverage):
    averagedplates = {}
    stddev = {}
    for key, plate in platestoaverage.items():
        valuedf = pd.DataFrame()
        devdf = pd.DataFrame()
        for col in plate.columns:
            valuecol, devcol = average_stddev(plate[col])
            valuedf[col] = valuecol
            devdf[col] = devcol
        rename_averaged_axes(valuedf)
        rename_averaged_axes(devdf)
        averagedplates[key] = valuedf
        stddev[key] = devdf
    return averagedplates, stddev

def generate_abdict(ab_sheet):
    ab_dict = {}
    for index, series in ab_sheet.iterrows():
        
        start_molarity = series["Concentration (mg/mL)"] / series["MW"] / (10 * series["Dilution"])
        if start_molarity != 0:
            log_mol = math.log(start_molarity, 10)
        else:
            log_mol = 0
        conc_arr = np.arange(log_mol, log_mol - 8, -1)
        
        ab_dict[index] = (series["Name"], conc_arr)
    return ab_dict



def pivot_excel(plates_dict): 
    
    writer = pd.ExcelWriter("FFLuc-RLuc.xlsx", engine = "openpyxl")

    for key, plate in plates_dict.items():
        unstack = plate.unstack()
        unstack.to_excel(writer, sheet_name = key)
    writer.save()

#*** Obsolete by using multiindexing ***
#Accepts a dictionary of plates, and preps each plate for reshaping via .pivot
#Adds an "n" column, and collapses indeces to 8 (to account for duplicates)

# def prep_pivot(platedict):
#     for plate in platedict.values():
#         plate["n"] = pd.Series([2,1]*len(plate/2))
#         plate.rename_axis("Column", axis = "columns", inplace = True)
#         plate.rename_axis("Row", axis = "index", inplace = True)
#         plate.index = plate.index.map(collapse_dups)

#Mapper function to pass into Series.map()
#Used to collapse the indeces from 1->16 to 1->8 to account for duplicate rows in 384 well format
# def collapse_dups(index):
#     if index % 2 == 0:
#         return index / 2
#     return index // 2 + 1
        
#Takes the dataframe parsed from raw format off of M5 and changes Columns to be 1->24, and changes rows to be A->P
#Mutative function, doesn't return a new dataframe, but changes the existing dataframe that is passed in
def rename_axes(df):
    rownames = dict(zip(list(range(0, 16)), list(string.ascii_lowercase)[0:17]))
    colnames = dict(zip(list(range(2, 26)), list(range(1, 25))))
    df.rename(index = rownames, inplace=True)
    df.rename(columns = colnames, inplace = True)

#Changes rows from A->H
def rename_averaged_axes(df):
    rownames = dict(zip(list(range(0, 8)), list(string.ascii_lowercase)[0:8]))
    df.rename(index = rownames, inplace=True)

In [2]:
eln_uploader = widgets.FileUpload(multiple = False)
display("Upload ELN w/ Functional Data and Antibodies Sheet (xlsx), and specify assay type")
display(eln_uploader)

'Upload ELN w/ Functional Data and Antibodies Sheet (xlsx), and specify assay type'

FileUpload(value={}, description='Upload')

In [26]:
elnname = list(eln_uploader.value.keys())[0]
rawdata = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']))
headers = [i for i in range(len(rawdata.columns))]
headers[0] = rawdata.columns[0]
rawdata = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']), names = headers)
ab_sheet = pd.read_excel(io.BytesIO(eln_uploader.value[elnname]['content']), sheet_name = "Antibody Sheet")
ab_sheet.index += 1
#rawdata
ab_sheet

,Unnamed: 0.1,Unnamed: 0,IGGP Ticket#,BPP Ticket# (If available),Plate ID/Barcode,Well ID,Name,Transfection cell line,Purification Method,Concentration (mg/mL),Transfection scale (mL),Volume (uL),Yield (ug),Lot#,Date Delivered,Format Row,Format Column,MW,Dilution
1,NaN,NaN,NaN,NaN,NaN,NaN,C-Kit Ligand,NaN,NaN,1.00,NaN,NaN,NaN,NaN,NaT,NaN,NaN,19000,10
2,1.0,NaN,IGGP-509,BPP-XXX,pUBX_IGGP-509_221129_P001,A1,TB578_JMS_001,Hek-293,Phynexus,1.72,8.0,366.057,629.61804,PROT16713,2022-11-30,A,1.0,150000,1
3,2.0,NaN,NaN,NaN,NaN,B1,TB578_JMS_002,Hek-293,Phynexus,2.00,8.0,344.724,689.44800,PROT16714,2022-11-30,B,1.0,150000,1
4,3.0,NaN,NaN,NaN,NaN,C1,TB578_JMS_003,Hek-293,Phynexus,2.01,8.0,347.215,697.90215,PROT16715,2022-11-30,C,1.0,150000,1
5,4.0,NaN,NaN,NaN,NaN,D1,TB578_JMS_004,Hek-293,Phynexus,2.84,8.0,266.899,757.99316,PROT16716,2022-11-30,D,1.0,150000,1
6,5.0,NaN,NaN,NaN,NaN,E1,TB578_JMS_005,Hek-293,Phynexus,1.64,8.0,374.660,614.44240,PROT16717,2022-11-30,E,1.0,150000,1
7,6.0,NaN,NaN,NaN,NaN,F1,TB578_JMS_006,Hek-293,Phynexus,1.87,8.0,365.495,683.47565,PROT16718,2022-11-30,F,1.0,150000,1
8,7.0,NaN,NaN,NaN,NaN,G1,TB578_JMS_008,Hek-293,Phynexus,0.95,8.0,394.770,375.03150,PROT16719,2022-11-30,G,1.0,150000,1
9,8.0,NaN,NaN,NaN,NaN,H1,TB578_JMS_009,Hek-293,Phynexus,1.37,8.0,382.863,524.52231,PROT16720,2022-11-30,H,1.0,150000,1
10,9.0,NaN,NaN,NaN,NaN,A2,TB578_JMS_012,Hek-293,Phynexus,1.10,8.0,360.311,396.34210,PROT16721,2022-11-30,A,2.0,150000,1
11,10.0,NaN,NaN,NaN,NaN,B2,TB578_JMS_015,Hek-293,Phynexus,0.28,8.0,379.851,106.35828,PROT16722,2022-11-30,B,2.0,150000,1
12,11.0,NaN,NaN,NaN,NaN,C2,TB578_JMS_016,Hek-293,Phynexus,1.96,8.0,353.979,693.79884,PROT16723,2022-11-30,C,2.0,150000,1
13,12.0,NaN,NaN,NaN,NaN,D2,TB578_JMS_018,Hek-293,Phynexus,1.66,8.0,303.903,504.47898,PROT16724,2022-11-30,D,2.0,150000,1
14,13.0,NaN,NaN,NaN,NaN,E2,TB578_JMS_022,Hek-293,Phynexus,1.93,8.0,373.630,721.10590,PROT16725,2022-11-30,E,2.0,150000,1
15,14.0,NaN,NaN,NaN,NaN,F2,TB578_JMS_030,Hek-293,Phynexus,1.90,8.0,409.256,777.58640,PROT16726,2022-11-30,F,2.0,150000,1
16,15.0,NaN,NaN,NaN,NaN,G2,TB578_JMS_031,Hek-293,Phynexus,1.75,8.0,398.880,698.04000,PROT16727,2022-11-30,G,2.0,150000,1
17,16.0,NaN,NaN,NaN,NaN,H2,TB578_JMS_042,Hek-293,Phynexus,1.85,8.0,400.657,741.21545,PROT16728,2022-11-30,H,2.0,150000,1
18,17.0,NaN,NaN,NaN,NaN,A3,TB578_JMS_078,Hek-293,Phynexus,1.69,8.0,389.214,657.77166,PROT16729,2022-11-30,A,3.0,150000,1
19,18.0,NaN,NaN,NaN,NaN,B3,TB578_JMS_086,Hek-293,Phynexus,0.39,8.0,375.780,146.55420,PROT16730,2022-11-30,B,3.0,150000,1
20,19.0,NaN,NaN,NaN,NaN,C3,TB578_JMS_117,Hek-293,Phynexus,2.24,8.0,379.889,850.95136,PROT16731,2022-11-30,C,3.0,150000,1
21,20.0,NaN,NaN,NaN,NaN,D3,TB578_JMS_143,Hek-293,Phynexus,0.00,8.0,294.332,0.00000,PROT16732,2022-11-30,D,3.0,150000,1
22,21.0,NaN,NaN,NaN,NaN,E3,TB578_JMS_1_Control,Hek-293,Phynexus,1.47,8.0,367.531,540.27057,PROT16733,2022-11-30,E,3.0,150000,1
23,22.0,NaN,NaN,NaN,NaN,F3,TB578_JMS_2_Control,Hek-293,Phynexus,1.11,8.0,359.863,399.44793,PROT16734,2022-11-30,F,3.0,150000,1
24,23.0,NaN,NaN,NaN,NaN,G3,TB578_JMS_3_Control,Hek-293,Phynexus,1.30,8.0,357.994,465.39220,PROT16735,2022-11-30,G,3.0,150000,1

In [41]:
#Returns a dictionary of series to correct concentrations of the passed in plate_dictionary {Name: Df} key value pairs
#Key of dictionary will be Antibody Name, Value will be the DataFrame with correct concentrations and n=1,2 pairs
def concentration_series(plate_dict, ab_dict):
    return_dict = {}
    for name, plate in plate_dict.items():
        
        for column_num in plate.columns:
            
            trueconc_arr = ab_dict[column_num][1]
            antibody_name = ab_dict[column_num][0]
            
            conc_mapper = dict(zip(np.arange(1,9), trueconc_arr))
            returndict[plate.loc[:, column_num].rename(index = conc_mapper, level = "Row")

numblocks = int(rawdata.columns[0][10:])

parsedplates = parse(rawdata, numblocks)
cleanplates = clean(parsedplates)
divideplates = divplate(cleanplates, "FFLuc", "RLuc")
correct_concentrations(divideplates, generate_abdict(ab_sheet))
divideplates
#pivot_excel(divideplates)

#averagedplates, stddevplates = average_plates(dividedplates)
#averagedplates

{1: -6.278753600952828, 2: -7.278753600952828, 3: -8.278753600952829, 4: -9.278753600952829, 5: -10.278753600952829, 6: -11.278753600952829, 7: -12.278753600952829, 8: -13.278753600952829}
Row         n
-6.278754   1    0.217149
            2    0.224453
-7.278754   1    0.192249
            2    0.174525
-8.278754   1    0.222474
            2    0.231861
-9.278754   1    0.190175
            2     0.20321
-10.278754  1    0.182514
            2    0.214211
-11.278754  1    0.594645
            2    0.665892
-12.278754  1    0.592297
            2    0.639412
-13.278754  1     0.91555
            2    1.334815
Name: 1, dtype: object
{1: -5.940562812148132, 2: -6.940562812148132, 3: -7.940562812148132, 4: -8.940562812148132, 5: -9.940562812148132, 6: -10.940562812148132, 7: -11.940562812148132, 8: -12.940562812148132}
Row         n
-5.940563   1    1.086462
            2    0.555694
-6.940563   1    0.572006
            2    0.628635
-7.940563   1    0.587639
            2    0.544752
-8.940563   1    0.535957
            2    0.503312
-9.940563   1    0.418184
            2    0.431799
-10.940563  1    0.329097
            2    0.316572
-11.940563  1    0.235465
            2     0.23396
-12.940563  1    0.231682
            2    0.266801
Name: 2, dtype: object
{1: -5.8750612633917, 2: -6.8750612633917, 3: -7.8750612633917, 4: -8.8750612633917, 5: -9.8750612633917, 6: -10.8750612633917, 7: -11.8750612633917, 8: -12.8750612633917}
Row         n
-5.875061   1    0.661782
            2    0.631486
-6.875061   1    0.644467
            2    0.523949
-7.875061   1    0.577927
            2    0.578447
-8.875061   1    0.505907
            2    0.509546
-9.875061   1    0.478079
            2     0.37008
-10.875061  1    0.322327
            2    0.364361
-11.875061  1    0.208367
            2    0.224876
-12.875061  1    0.267288
            2    0.387613
Name: 3, dtype: object
{1: -5.872895201635192, 2: -6.872895201635192, 3: -7.872895201635192, 4: -8.872895201635192, 5: -9.872895201635192, 6: -10.872895201635192, 7: -11.872895201635192, 8: -12.872895201635192}
Row         n
-5.872895   1    0.668481
            2    0.718594
-6.872895   1    0.631331
            2    0.613473
-7.872895   1    0.633983
            2    0.608874
-8.872895   1    0.757347
            2    0.596202
-9.872895   1    0.644681
            2    0.535827
-10.872895  1    0.527992
            2    0.491873
-11.872895  1    0.334976
            2    0.346785
-12.872895  1    0.296687
            2    0.266455
Name: 4, dtype: object
{1: -5.722772919008643, 2: -6.722772919008643, 3: -7.722772919008643, 4: -8.722772919008644, 5: -9.722772919008644, 6: -10.722772919008644, 7: -11.722772919008644, 8: -12.722772919008644}
Row         n
-5.722773   1    0.519698
            2    0.544945
-6.722773   1    0.473777
            2    0.433246
-7.722773   1    0.547651
            2    0.513309
-8.722773   1    0.552426
            2    0.541569
-9.722773   1    0.563601
            2    0.535133
-10.722773  1    0.490998
            2      0.5171
-11.722773  1    0.398972
            2    0.427991
-12.722773  1    0.411079
            2    0.350772
Name: 5, dtype: object
{1: -5.9612474110079825, 2: -6.9612474110079825, 3: -7.9612474110079825, 4: -8.961247411007982, 5: -9.961247411007982, 6: -10.961247411007982, 7: -11.961247411007982, 8: -12.961247411007982}
Row         n
-5.961247   1    0.529098
            2    0.498918
-6.961247   1    0.393883
            2    0.459894
-7.961247   1    0.454868
            2    0.523703
-8.961247   1    0.470434
            2    0.460669
-9.961247   1    0.456253
            2    0.444323
-10.961247  1    0.382774
            2    0.319966
-11.961247  1    0.270236
            2    0.274052
-12.961247  1    0.256356
            2    0.219421
Name: 6, dtype: object
{1: -5.904249652519182, 2: -6.904249652519182, 3: -7.904249652519182, 4: -8.904249652519182, 5: -9.904249652519182, 6: -10.904249652519182, 7: -11.904249652519182, 8: -12.904249652519182}
Row        n
-5.90425   1    0.582049
           2    0.685112
-6.90425   1    0.547083
           2    0.588619
-7.90425   1    0.575057
           2    0.531147
-8.90425   1    0.549698
           2     0.49594
-9.90425   1    0.425282
           2    0.454107
-10.90425  1     0.38986
           2    0.408541
-11.90425  1    0.355037
           2    0.321439
-12.90425  1    0.386772
           2    0.255872
Name: 7, dtype: object
{1: -6.198367653766833, 2: -7.198367653766833, 3: -8.198367653766834, 4: -9.198367653766834, 5: -10.198367653766834, 6: -11.198367653766834, 7: -12.198367653766834, 8: -13.198367653766834}
Row         n
-6.198368   1    0.736408
            2    0.565562
-7.198368   1     0.49564
            2    0.525308
-8.198368   1    0.612923
            2    0.528353
-9.198368   1    0.520224
            2    0.608636
-10.198368  1    0.518282
            2    0.478908
-11.198368  1    0.270321
            2    0.284691
-12.198368  1    0.261984
            2    0.249985
-13.198368  1     0.19899
            2    0.262382
Name: 8, dtype: object
{1: -6.039370691899274, 2: -7.039370691899274, 3: -8.039370691899274, 4: -9.039370691899274, 5: -10.039370691899274, 6: -11.039370691899274, 7: -12.039370691899274, 8: -13.039370691899274}
Row         n
-6.039371   1    0.652395
            2    0.562412
-7.039371   1    0.478619
            2    0.510368
-8.039371   1    0.571605
            2    0.588246
-9.039371   1    0.536741
            2     0.59377
-10.039371  1    0.625181
            2    0.573059
-11.039371  1     0.64465
            2    0.741758
-12.039371  1     0.56645
            2    0.759127
-13.039371  1    0.782471
            2    0.755539
Name: 9, dtype: object
{1: -6.134698573897456, 2: -7.134698573897456, 3: -8.134698573897456, 4: -9.134698573897456, 5: -10.134698573897456, 6: -11.134698573897456, 7: -12.134698573897456, 8: -13.134698573897456}
Row         n
-6.134699   1    0.644956
            2    0.537288
-7.134699   1    0.425326
            2    0.607071
-8.134699   1    0.583501
            2    0.595724
-9.134699   1    0.577761
            2    0.509165
-10.134699  1    0.665504
            2    0.705583
-11.134699  1    0.830103
            2    0.860645
-12.134699  1    0.803207
            2    0.879387
-13.134699  1    0.912238
            2    1.003688
Name: 10, dtype: object
{1: -6.728933227713461, 2: -7.728933227713461, 3: -8.728933227713462, 4: -9.728933227713462, 5: -10.728933227713462, 6: -11.728933227713462, 7: -12.728933227713462, 8: -13.728933227713462}
Row         n
-6.728933   1     0.48152
            2    0.485285
-7.728933   1    0.370816
            2    0.375972
-8.728933   1    0.409366
            2    0.438996
-9.728933   1    0.483025
            2    0.313565
-10.728933  1    0.403594
            2    0.367335
-11.728933  1     0.42339
            2    0.414634
-12.728933  1    0.412945
            2    0.480663
-13.728933  1    0.462302
            2    0.634429
Name: 11, dtype: object
{1: -5.883835187699205, 2: -6.883835187699205, 3: -7.883835187699205, 4: -8.883835187699205, 5: -9.883835187699205, 6: -10.883835187699205, 7: -11.883835187699205, 8: -12.883835187699205}
Row         n
-5.883835   1    0.483949
            2    0.955483
-6.883835   1      0.5389
            2    0.469877
-7.883835   1    0.499419
            2    0.533416
-8.883835   1    0.590353
            2     0.39803
-9.883835   1    0.630278
            2    0.569508
-10.883835  1    0.530664
            2     0.52979
-11.883835  1    0.564615
            2    0.492811
-12.883835  1    0.482749
            2    0.526794
Name: 12, dtype: object
{1: -5.9559831710156255, 2: -6.9559831710156255, 3: -7.9559831710156255, 4: -8.955983171015625, 5: -9.955983171015625, 6: -10.955983171015625, 7: -11.955983171015625, 8: -12.955983171015625}
Row         n
-5.955983   1    0.715515
            2    0.916894
-6.955983   1    0.586668
            2    0.623308
-7.955983   1    0.602669
            2    0.765827
-8.955983   1    0.621174
            2     0.51664
-9.955983   1    0.787025
            2    0.814125
-10.955983  1    0.941614
            2    1.008364
-11.955983  1    0.893431
            2    0.717231
-12.955983  1    0.548584
            2    0.927891
Name: 13, dtype: object
{1: -5.890533950047907, 2: -6.890533950047907, 3: -7.890533950047907, 4: -8.890533950047907, 5: -9.890533950047907, 6: -10.890533950047907, 7: -11.890533950047907, 8: -12.890533950047907}
Row         n
-5.890534   1    0.677351
            2    0.623487
-6.890534   1     0.52452
            2    0.713837
-7.890534   1    0.687494
            2    0.736704
-8.890534   1    0.556883
            2    0.634515
-9.890534   1    0.620719
            2    0.622512
-10.890534  1    0.625164
            2    0.530099
-11.890534  1    0.565956
            2    0.600397
-12.890534  1    0.359397
            2    0.347494
Name: 14, dtype: object
{1: -5.897337658102852, 2: -6.897337658102852, 3: -7.897337658102852, 4: -8.897337658102852, 5: -9.897337658102852, 6: -10.897337658102852, 7: -11.897337658102852, 8: -12.897337658102852}
Row         n
-5.897338   1    0.869006
            2    0.657933
-6.897338   1    0.476359
            2    0.516423
-7.897338   1    0.567583
            2    0.630072
-8.897338   1    0.645602
            2    0.599818
-9.897338   1    0.546529
            2    0.498509
-10.897338  1    0.246655
            2    0.274831
-11.897338  1     0.26578
            2    0.263313
-12.897338  1    0.235208
            2    0.278349
Name: 15, dtype: object
{1: -5.933053210369387, 2: -6.933053210369387, 3: -7.933053210369387, 4: -8.933053210369387, 5: -9.933053210369387, 6: -10.933053210369387, 7: -11.933053210369387, 8: -12.933053210369387}
Row         n
-5.933053   1     0.56605
            2    0.417079
-6.933053   1    0.488923
            2    0.473846
-7.933053   1    0.427996
            2    0.468558
-8.933053   1    0.468552
            2    0.547463
-9.933053   1    0.449331
            2    0.444897
-10.933053  1    0.410257
            2    0.446289
-11.933053  1    0.296063
            2    0.355321
-12.933053  1    0.257084
            2    0.311675
Name: 16, dtype: object
{1: -5.908919530652667, 2: -6.908919530652667, 3: -7.908919530652667, 4: -8.908919530652668, 5: -9.908919530652668, 6: -10.908919530652668, 7: -11.908919530652668, 8: -12.908919530652668}
Row        n
-5.90892   1    0.546884
           2    0.731547
-6.90892   1    0.523909
           2    0.636121
-7.90892   1    0.645017
           2    0.584892
-8.90892   1    0.590142
           2    0.580895
-9.90892   1    0.516602
           2    0.652399
-10.90892  1     0.56934
           2    0.625378
-11.90892  1    0.409067
           2    0.535695
-12.90892  1    0.352671
           2    0.316915
Name: 17, dtype: object
{1: -5.9482045544420075, 2: -6.9482045544420075, 3: -7.9482045544420075, 4: -8.948204554442007, 5: -9.948204554442007, 6: -10.948204554442007, 7: -11.948204554442007, 8: -12.948204554442007}
Row         n
-5.948205   1    0.698611
            2    0.594693
-6.948205   1    0.538983
            2     0.65945
-7.948205   1    0.665128
            2    0.625331
-8.948205   1    0.599486
            2    0.660039
-9.948205   1    0.545051
            2    0.779388
-10.948205  1    0.621601
            2    0.596338
-11.948205  1    0.523495
            2    0.498499
-12.948205  1    0.350806
            2    0.330645
Name: 18, dtype: object
{1: -6.585026652029182, 2: -7.585026652029182, 3: -8.585026652029182, 4: -9.585026652029182, 5: -10.585026652029182, 6: -11.585026652029182, 7: -12.585026652029182, 8: -13.585026652029182}
Row         n
-6.585027   1    0.759804
            2    0.738752
-7.585027   1    0.609146
            2    0.775997
-8.585027   1    0.704606
            2     0.66103
-9.585027   1    0.626409
            2    0.683722
-10.585027  1    0.719504
            2    0.685213
-11.585027  1    0.762117
            2    0.798445
-12.585027  1    0.758413
            2    0.775745
-13.585027  1    0.587666
            2      0.6062
Name: 19, dtype: object
{1: -5.825843240721518, 2: -6.825843240721518, 3: -7.825843240721518, 4: -8.825843240721518, 5: -9.825843240721518, 6: -10.825843240721518, 7: -11.825843240721518, 8: -12.825843240721518}
Row         n
-5.825843   1    0.733281
            2    0.638969
-6.825843   1    0.558511
            2    0.666697
-7.825843   1    0.709633
            2    0.672517
-8.825843   1    0.707486
            2    0.717434
-9.825843   1    0.684328
            2    0.687263
-10.825843  1    0.638912
            2    0.560405
-11.825843  1    0.582843
            2    0.661435
-12.825843  1    0.261495
            2    0.260413
Name: 20, dtype: object
{1: 0, 2: -1, 3: -2, 4: -3, 5: -4, 6: -5, 7: -6, 8: -7}
Row  n
 0   1    0.700667
     2    0.667963
-1   1    0.597354
     2     0.70817
-2   1    0.649244
     2     0.71651
-3   1    0.658132
     2    0.798414
-4   1    0.811243
     2    1.005691
-5   1    1.054365
     2    0.871314
-6   1    0.817372
     2    0.887762
-7   1    0.649768
     2    0.590353
Name: 21, dtype: object
{1: -6.008773924307504, 2: -7.008773924307504, 3: -8.008773924307505, 4: -9.008773924307505, 5: -10.008773924307505, 6: -11.008773924307505, 7: -12.008773924307505, 8: -13.008773924307505}
Row         n
-6.008774   1    0.784328
            2    0.615986
-7.008774   1    0.647102
            2    0.574439
-8.008774   1    0.682019
            2    0.248984
-9.008774   1    0.835468
            2    0.856007
-10.008774  1    0.479461
            2     0.53908
-11.008774  1    0.274667
            2    0.306359
-12.008774  1    0.300912
            2    0.296701
-13.008774  1    0.357577
            2    0.400051
Name: 22, dtype: object
{1: -6.130768280269024, 2: -7.130768280269024, 3: -8.130768280269024, 4: -9.130768280269024, 5: -10.130768280269024, 6: -11.130768280269024, 7: -12.130768280269024, 8: -13.130768280269024}
Row         n
-6.130768   1    1.109009
            2    0.969992
-7.130768   1    1.083694
            2    1.398696
-8.130768   1    1.510361
            2    1.172981
-9.130768   1    1.041226
            2    1.436766
-10.130768  1    0.684645
            2    0.772331
-11.130768  1    0.328656
            2    0.360742
-12.130768  1    0.312246
            2    0.329513
-13.130768  1    0.493047
            2    0.625137
Name: 23, dtype: object
{1: -6.062147906748844, 2: -7.062147906748844, 3: -8.062147906748844, 4: -9.062147906748844, 5: -10.062147906748844, 6: -11.062147906748844, 7: -12.062147906748844, 8: -13.062147906748844}
Row         n
-6.062148   1    1.598722
            2    1.410621
-7.062148   1    1.402331
            2      1.2406
-8.062148   1    1.371744
            2    1.514303
-9.062148   1    1.414481
            2    1.330881
-10.062148  1    1.503592
            2    1.287016
-11.062148  1    0.802842
            2    0.794416
-12.062148  1    0.760827
            2    0.904092
-13.062148  1    0.888456
            2     0.72147
Name: 24, dtype: object
{1: -6.278753600952828, 2: -7.278753600952828, 3: -8.278753600952829, 4: -9.278753600952829, 5: -10.278753600952829, 6: -11.278753600952829, 7: -12.278753600952829, 8: -13.278753600952829}
Row         n
-6.278754   1    0.217149
            2    0.224453
-7.278754   1    0.192249
            2    0.174525
-8.278754   1    0.222474
            2    0.231861
-9.278754   1    0.190175
            2     0.20321
-10.278754  1    0.182514
            2    0.214211
-11.278754  1    0.594645
            2    0.665892
-12.278754  1    0.592297
            2    0.639412
-13.278754  1     0.91555
            2    1.334815
Name: 1, dtype: object
{1: -5.940562812148132, 2: -6.940562812148132, 3: -7.940562812148132, 4: -8.940562812148132, 5: -9.940562812148132, 6: -10.940562812148132, 7: -11.940562812148132, 8: -12.940562812148132}
Row         n
-5.940563   1    1.086462
            2    0.555694
-6.940563   1    0.572006
            2    0.628635
-7.940563   1    0.587639
            2    0.544752
-8.940563   1    0.535957
            2    0.503312
-9.940563   1    0.418184
            2    0.431799
-10.940563  1    0.329097
            2    0.316572
-11.940563  1    0.235465
            2     0.23396
-12.940563  1    0.231682
            2    0.266801
Name: 2, dtype: object
{1: -5.8750612633917, 2: -6.8750612633917, 3: -7.8750612633917, 4: -8.8750612633917, 5: -9.8750612633917, 6: -10.8750612633917, 7: -11.8750612633917, 8: -12.8750612633917}
Row         n
-5.875061   1    0.661782
            2    0.631486
-6.875061   1    0.644467
            2    0.523949
-7.875061   1    0.577927
            2    0.578447
-8.875061   1    0.505907
            2    0.509546
-9.875061   1    0.478079
            2     0.37008
-10.875061  1    0.322327
            2    0.364361
-11.875061  1    0.208367
            2    0.224876
-12.875061  1    0.267288
            2    0.387613
Name: 3, dtype: object
{1: -5.872895201635192, 2: -6.872895201635192, 3: -7.872895201635192, 4: -8.872895201635192, 5: -9.872895201635192, 6: -10.872895201635192, 7: -11.872895201635192, 8: -12.872895201635192}
Row         n
-5.872895   1    0.668481
            2    0.718594
-6.872895   1    0.631331
            2    0.613473
-7.872895   1    0.633983
            2    0.608874
-8.872895   1    0.757347
            2    0.596202
-9.872895   1    0.644681
            2    0.535827
-10.872895  1    0.527992
            2    0.491873
-11.872895  1    0.334976
            2    0.346785
-12.872895  1    0.296687
            2    0.266455
Name: 4, dtype: object
{1: -5.722772919008643, 2: -6.722772919008643, 3: -7.722772919008643, 4: -8.722772919008644, 5: -9.722772919008644, 6: -10.722772919008644, 7: -11.722772919008644, 8: -12.722772919008644}
Row         n
-5.722773   1    0.519698
            2    0.544945
-6.722773   1    0.473777
            2    0.433246
-7.722773   1    0.547651
            2    0.513309
-8.722773   1    0.552426
            2    0.541569
-9.722773   1    0.563601
            2    0.535133
-10.722773  1    0.490998
            2      0.5171
-11.722773  1    0.398972
            2    0.427991
-12.722773  1    0.411079
            2    0.350772
Name: 5, dtype: object
{1: -5.9612474110079825, 2: -6.9612474110079825, 3: -7.9612474110079825, 4: -8.961247411007982, 5: -9.961247411007982, 6: -10.961247411007982, 7: -11.961247411007982, 8: -12.961247411007982}
Row         n
-5.961247   1    0.529098
            2    0.498918
-6.961247   1    0.393883
            2    0.459894
-7.961247   1    0.454868
            2    0.523703
-8.961247   1    0.470434
            2    0.460669
-9.961247   1    0.456253
            2    0.444323
-10.961247  1    0.382774
            2    0.319966
-11.961247  1    0.270236
            2    0.274052
-12.961247  1    0.256356
            2    0.219421
Name: 6, dtype: object
{1: -5.904249652519182, 2: -6.904249652519182, 3: -7.904249652519182, 4: -8.904249652519182, 5: -9.904249652519182, 6: -10.904249652519182, 7: -11.904249652519182, 8: -12.904249652519182}
Row        n
-5.90425   1    0.582049
           2    0.685112
-6.90425   1    0.547083
           2    0.588619
-7.90425   1    0.575057
           2    0.531147
-8.90425   1    0.549698
           2     0.49594
-9.90425   1    0.425282
           2    0.454107
-10.90425  1     0.38986
           2    0.408541
-11.90425  1    0.355037
           2    0.321439
-12.90425  1    0.386772
           2    0.255872
Name: 7, dtype: object
{1: -6.198367653766833, 2: -7.198367653766833, 3: -8.198367653766834, 4: -9.198367653766834, 5: -10.198367653766834, 6: -11.198367653766834, 7: -12.198367653766834, 8: -13.198367653766834}
Row         n
-6.198368   1    0.736408
            2    0.565562
-7.198368   1     0.49564
            2    0.525308
-8.198368   1    0.612923
            2    0.528353
-9.198368   1    0.520224
            2    0.608636

{'CD117 SRF No1 FFLuc-RLuc': Column        1         2         3         4         5         6         7   \
 Row n
 1   1   0.217149  1.086462  0.661782  0.668481  0.519698  0.529098  0.582049
     2   0.224453  0.555694  0.631486  0.718594  0.544945  0.498918  0.685112
 2   1   0.192249  0.572006  0.644467  0.631331  0.473777  0.393883  0.547083
     2   0.174525  0.628635  0.523949  0.613473  0.433246  0.459894  0.588619
 3   1   0.222474  0.587639  0.577927  0.633983  0.547651  0.454868  0.575057
     2   0.231861  0.544752  0.578447  0.608874  0.513309  0.523703  0.531147
 4   1   0.190175  0.535957  0.505907  0.757347  0.552426  0.470434  0.549698
     2    0.20321  0.503312  0.509546  0.596202  0.541569  0.460669   0.49594
 5   1   0.182514  0.418184  0.478079  0.644681  0.563601  0.456253  0.425282
     2   0.214211  0.431799   0.37008  0.535827  0.535133  0.444323  0.454107
 6   1   0.594645  0.329097  0.322327  0.527992  0.490998  0.382774   0.38986
     2   0.665892  0.316572  0.364361  0.491873    0.5171  0.319966  0.408541
 7   1   0.592297  0.235465  0.208367  0.334976  0.398972  0.270236  0.355037
     2   0.639412   0.23396  0.224876  0.346785  0.427991  0.274052  0.321439
 8   1    0.91555  0.231682  0.267288  0.296687  0.411079  0.256356  0.386772
     2   1.334815  0.266801  0.387613  0.266455  0.350772  0.219421  0.255872

 Column        8         9         10  ...        15        16        17  \
 Row n                                 ...
 1   1   0.736408  0.652395  0.644956  ...  0.869006   0.56605  0.546884
     2   0.565562  0.562412  0.537288  ...  0.657933  0.417079  0.731547
 2   1    0.49564  0.478619  0.425326  ...  0.476359  0.488923  0.523909
     2   0.525308  0.510368  0.607071  ...  0.516423  0.473846  0.636121
 3   1   0.612923  0.571605  0.583501  ...  0.567583  0.427996  0.645017
     2   0.528353  0.588246  0.595724  ...  0.630072  0.468558  0.584892
 4   1   0.520224  0.536741  0.577761  ...  0.645602  0.468552  0.590142
     2   0.608636   0.59377  0.509165  ...  0.599818  0.547463  0.580895
 5   1   0.518282  0.625181  0.665504  ...  0.546529  0.449331  0.516602
     2   0.478908  0.573059  0.705583  ...  0.498509  0.444897  0.652399
 6   1   0.270321   0.64465  0.830103  ...  0.246655  0.410257   0.56934
     2   0.284691  0.741758  0.860645  ...  0.274831  0.446289  0.625378
 7   1   0.261984   0.56645  0.803207  ...   0.26578  0.296063  0.409067
     2   0.249985  0.759127  0.879387  ...  0.263313  0.355321  0.535695
 8   1    0.19899  0.782471  0.912238  ...  0.235208  0.257084  0.352671
     2   0.262382  0.755539  1.003688  ...  0.278349  0.311675  0.316915

 Column        18        19        20        21        22        23        24
 Row n
 1   1   0.698611  0.759804  0.733281  0.700667  0.784328  1.109009  1.598722
     2   0.594693  0.738752  0.638969  0.667963  0.615986  0.969992  1.410621
 2   1   0.538983  0.609146  0.558511  0.597354  0.647102  1.083694  1.402331
     2    0.65945  0.775997  0.666697   0.70817  0.574439  1.398696    1.2406
 3   1   0.665128  0.704606  0.709633  0.649244  0.682019  1.510361  1.371744
     2   0.625331   0.66103  0.672517   0.71651  0.248984  1.172981  1.514303
 4   1   0.599486  0.626409  0.707486  0.658132  0.835468  1.041226  1.414481
     2   0.660039  0.683722  0.717434  0.798414  0.856007  1.436766  1.330881
 5   1   0.545051  0.719504  0.684328  0.811243  0.479461  0.684645  1.503592
     2   0.779388  0.685213  0.687263  1.005691   0.53908  0.772331  1.287016
 6   1   0.621601  0.762117  0.638912  1.054365  0.274667  0.328656  0.802842
     2   0.596338  0.798445  0.560405  0.871314  0.306359  0.360742  0.794416
 7   1   0.523495  0.758413  0.582843  0.817372  0.300912  0.312246  0.760827
     2   0.498499  0.775745  0.661435  0.887762  0.296701  0.329513  0.904092
 8   1   0.350806  0.587666  0.261495  0.649768  0.357577  0.493047  0.888456
     2   0.330645    0.6062  0.260413  0.590353  0.400051  0.625137   0.72147

 [16 rows x 24 columns],
 'CD117 SRF No2 FFLuc-RLuc': Column        1         2         3         4         5         6         7   \
 Row n
 1   1   0.217149  1.086462  0.661782  0.668481  0.519698  0.529098  0.582049
     2   0.224453  0.555694  0.631486  0.718594  0.544945  0.498918  0.685112
 2   1   0.192249  0.572006  0.644467  0.631331  0.473777  0.393883  0.547083
     2   0.174525  0.628635  0.523949  0.613473  0.433246  0.459894  0.588619
 3   1   0.222474  0.587639  0.577927  0.633983  0.547651  0.454868  0.575057
     2   0.231861  0.544752  0.578447  0.608874  0.513309  0.523703  0.531147
 4   1   0.190175  0.535957  0.505907  0.757347  0.552426  0.470434  0.549698
     2    0.20321  0.503312  0.509546  0.596202  0.541569  0.460669   0.49594
 5   1   0.182514  0.418184  0.478079  0.644681  0.563601  0.456253  0.425282
     2   0.214211  0.431799   0.37008  0.535827  0.535133  0.444323  0.454107
 6   1   0.594645  0.329097  0.322327  0.527992  0.490998  0.382774   0.38986
     2   0.665892  0.316572  0.364361  0.491873    0.5171  0.319966  0.408541
 7   1   0.592297  0.235465  0.208367  0.334976  0.398972  0.270236  0.355037
     2   0.639412   0.23396  0.224876  0.346785  0.427991  0.274052  0.321439
 8   1    0.91555  0.231682  0.267288  0.296687  0.411079  0.256356  0.386772
     2   1.334815  0.266801  0.387613  0.266455  0.350772  0.219421  0.255872

 Column        8         9         10  ...        15        16        17  \
 Row n                                 ...
 1   1   0.736408  0.652395  0.644956  ...  0.869006   0.56605  0.546884
     2   0.565562  0.562412  0.537288  ...  0.657933  0.417079  0.731547
 2   1    0.49564  0.478619  0.425326  ...  0.476359  0.488923  0.523909
     2   0.525308  0.510368  0.607071  ...  0.516423  0.473846  0.636121
 3   1   0.612923  0.571605  0.583501  ...  0.567583  0.427996  0.645017
     2   0.528353  0.588246  0.595724  ...  0.630072  0.468558  0.584892
 4   1   0.520224  0.536741  0.577761  ...  0.645602  0.468552  0.590142
     2   0.608636   0.59377  0.509165  ...  0.599818  0.547463  0.580895
 5   1   0.518282  0.625181  0.665504  ...  0.546529  0.449331  0.516602
     2   0.478908  0.573059  0.705583  ...  0.498509  0.444897  0.652399
 6   1   0.270321   0.64465  0.830103  ...  0.246655  0.410257   0.56934
     2   0.284691  0.741758  0.860645  ...  0.274831  0.446289  0.625378
 7   1   0.261984   0.56645  0.803207  ...   0.26578  0.296063  0.409067
     2   0.249985  0.759127  0.879387  ...  0.263313  0.355321  0.535695
 8   1    0.19899  0.782471  0.912238  ...  0.235208  0.257084  0.352671
     2   0.262382  0.755539  1.003688  ...  0.278349  0.311675  0.316915

 Column        18        19        20        21        22        23        24
 Row n
 1   1   0.698611  0.759804  0.733281  0.700667  0.784328  1.109009  1.598722
     2   0.594693  0.738752  0.638969  0.667963  0.615986  0.969992  1.410621
 2   1   0.538983  0.609146  0.558511  0.597354  0.647102  1.083694  1.402331
     2    0.65945  0.775997  0.666697   0.70817  0.574439  1.398696    1.2406
 3   1   0.665128  0.704606  0.709633  0.649244  0.682019  1.510361  1.371744
     2   0.625331   0.66103  0.672517   0.71651  0.248984  1.172981  1.514303
 4   1   0.599486  0.626409  0.707486  0.658132  0.835468  1.041226  1.414481
     2   0.660039  0.683722  0.717434  0.798414  0.856007  1.436766  1.330881
 5   1   0.545051  0.719504  0.684328  0.811243  0.479461  0.684645  1.503592
     2   0.779388  0.685213  0.687263  1.005691   0.53908  0.772331  1.287016
 6   1   0.621601  0.762117  0.638912  1.054365  0.274667  0.328656  0.802842
     2   0.596338  0.798445  0.560405  0.871314  0.306359  0.360742  0.794416
 7   1   0.523495  0.758413  0.582843  0.817372  0.300912  0.312246  0.760827
     2   0.498499  0.775745  0.661435  0.887762  0.296701  0.329513  0.904092
 8   1   0.350806  0.587666  0.261495  0.649768  0.357577  0.493047  0.888456
     2   0.330645    0.6062  0.260413  0.590353  0.400051  0.625137   0.72147

 [16 rows x 24 columns],
 'CD117 SRF FFLuc-RLuc': Column        1         2         3         4         5         6         7   \
 Row n
 1   1   1.109944  1.261493  1.526483  1.320267  1.230642  1.253276  1.573763
     2   0.709899  0.684996  1.361002  1.140189  0.844277  0.581615  1.129011
 2   1   0.651972   0.70053   1.03416  1.506122  0.992126  0.905175   1.40722
     2   0.717416  0.719127   1.34364  1.316936  1.238263  0.960037  1.586049
 3   1   0.813016  0.742984  1.327848  1.111835  0.813254   1.04033  1.367343
     2   0.822846  1.167963   1.10427   1.29249  0.741235  0.891898  1.220999
 4   1   0.600743  1.215148  1.110814  1.217289  0.863478  0.960699  1.118422
     2   0.737549  2.143318  1.324646  1.253984  0.956025  0.922164  1.044649
 5   1     0.9985  1.419154    1.3408  1.089712  0.980421  0.940341  1.135418
     2   0.841402  1.217284  1.247433  1.175823  0.960626  0.997077  1.368371
 6   1   1.439152  1.179845  0.963653  1.129975  0.931421  0.957068  1.052331
     2   1.316795  1.121421  1.106187  1.518536  0.888908  0.892609  1.441326
 7   1   1.441548  1.144163  1.117808  1.224979  1.134211  0.825579  0.758345
     2   1.217813  0.633559  0.599374  1.126867  1.115338  0.766428  0.697852
 8   1   1.434168  0.677774  0.537335   0.65486  0.842461  0.567832  0.585981
     2   1.575614  0.776925  0.566275  0.721236  0.838194  0.531133  0.755487

 Column        8         9         10  ...        15        16        17  \
 Row n                                 ...
 1   1   1.241471  1.363353  1.408357  ...  1.473849  1.136629  1.476294
     2   1.348634  1.167435  1.366666  ...  1.024697  1.336292   1.36734
 2   1    1.02853   1.00701   1.20599  ...  1.031524  1.323429  1.119248
     2   1.109035  1.042134  1.227527  ...  1.346373  1.136553  1.214242
 3   1   1.017181   1.06688  0.975953  ...  1.256951  1.205834  1.169007
     2   0.935243  1.010677  1.159269  ...  1.098868  0.708613  0.931391
 4   1   1.265149  1.114741  1.028364  ...  1.099002   1.00006  1.149396
     2   1.149027   1.17637  1.078039  ...  1.228732  0.986364  1.231569
 5   1   0.954015  0.978727  1.113629  ...  0.881499  0.933927  1.225758
     2   0.921019  1.137717  1.132645  ...  0.918997  1.048351  1.016418
 6   1   0.915047  0.989654  1.200836  ...  0.781435  0.956983  0.984622
     2   0.984116  1.120221  1.203555  ...  0.674579  0.968893  1.326825
 7   1   0.812279  1.096842  1.124504  ...  0.598518   0.87173  1.109751
     2   0.677354  1.186819  1.105258  ...  0.663704  0.774233  1.117734
 8   1   0.566395  1.026164   1.66112  ...  0.531948  0.524759  0.791106
     2   0.825943  1.400345  1.618258  ...  0.613954  0.616392  0.681788

 Column        18        19        20        21        22        23        24
 Row n
 1   1   1.293568  1.584012  1.498842  1.527416  0.681752  1.235943  1.482119
     2   0.877104  1.355574  1.447675  1.373839  0.694039  1.233268  1.371391
 2   1   1.070257  1.506896  1.405057   1.38889  1.366892  1.054715  1.640524
     2   1.171968  1.286381  1.403064  0.962392  0.774977  1.299858  1.603204
 3   1   1.058245  1.295574  1.189074  1.149897  0.514989  1.258149  1.323803
     2   1.233752  1.086928  1.170823  0.955438  1.630705  1.008565  1.425043
 4   1   1.329069  1.235277  1.425209  1.195507  1.015781  1.217877  1.621053
     2   1.273124  1.194377  1.161912  1.013034  0.657328    1.2006  1.381117
 5   1   0.612035  1.029446  1.240478  1.138335  0.588437   0.85365   1.04164
     2   1.072564  1.428887  1.283785  1.169691  0.582809  0.830063  1.156541
 6   1   1.270751  1.084566  1.382592  1.259612  0.525959  0.567801  0.803087
     2   1.175391  1.053275  1.067154  1.384303   0.65741  0.589696   0.62136
 7   1   1.142034  1.105313  1.461059  1.287886  0.582935  0.466938  0.501335
     2   0.996405  1.090792  1.203555  1.024209  0.660705  0.550086  0.602401
 8   1   0.721437  0.969346  0.755699  1.018152  0.444068  0.438299  0.728199
     2   0.668404  1.236238  0.943522  1.474371   0.63107  0.452096   0.61803

 [16 rows x 24 columns]}

In [17]:


# tt = divideplates['CD117 SRF FFLuc-RLuc'].loc[:, 1]
# tt = tt.rename(index = concentration, level = "Row").rename_axis(index = {"Row" : "Concentration"})
# tt
#tt.plot(kind='scatter', x = "Concentration", y = 'n')

NameError: name 'plate_dict' is not defined

In [ ]:
generator = ab_sheet.iterrows()
index, data = next(ab_sheet.iterrows())